/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class CollatableReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CollatableReader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CollatableReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_CollatableReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CollatableReader(Slice arg0) {
    this(cbforestJNI.new_CollatableReader(Slice.getCPtr(arg0), arg0), true);
  }

  public Slice data() {
    long cPtr = cbforestJNI.CollatableReader_data(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public int peekTag() {
    return cbforestJNI.CollatableReader_peekTag(swigCPtr, this);
  }

  public long readInt() {
    return cbforestJNI.CollatableReader_readInt(swigCPtr, this);
  }

  public double readDouble() {
    return cbforestJNI.CollatableReader_readDouble(swigCPtr, this);
  }

  public Slice readString() {
    long cPtr = cbforestJNI.CollatableReader_readString(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public Slice read() {
    long cPtr = cbforestJNI.CollatableReader_read(swigCPtr, this);
    return (cPtr == 0) ? null : new Slice(cPtr, false);
  }

  public void beginArray() {
    cbforestJNI.CollatableReader_beginArray(swigCPtr, this);
  }

  public void endArray() {
    cbforestJNI.CollatableReader_endArray(swigCPtr, this);
  }

  public void beginMap() {
    cbforestJNI.CollatableReader_beginMap(swigCPtr, this);
  }

  public void endMap() {
    cbforestJNI.CollatableReader_endMap(swigCPtr, this);
  }

  public String dump() {
    return cbforestJNI.CollatableReader_dump(swigCPtr, this);
  }

}
