/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class EmitFn {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EmitFn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmitFn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_EmitFn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void call(Collatable key, Collatable value) {
    cbforestJNI.EmitFn_call(swigCPtr, this, Collatable.getCPtr(key), key, Collatable.getCPtr(value), value);
  }

}
