/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class KeyStoreWriter extends KeyStore {
  private long swigCPtr;

  protected KeyStoreWriter(long cPtr, boolean cMemoryOwn) {
    super(cbforestJNI.KeyStoreWriter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyStoreWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        cbforestJNI.delete_KeyStoreWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public java.math.BigInteger set(Slice arg0, Slice arg1, Slice arg2) {
    return cbforestJNI.KeyStoreWriter_set__SWIG_0(swigCPtr, this, Slice.getCPtr(arg0), arg0, Slice.getCPtr(arg1), arg1, Slice.getCPtr(arg2), arg2);
  }

  public java.math.BigInteger set(Slice arg0, Slice arg1) {
    return cbforestJNI.KeyStoreWriter_set__SWIG_1(swigCPtr, this, Slice.getCPtr(arg0), arg0, Slice.getCPtr(arg1), arg1);
  }

  public void write(Document arg0) {
    cbforestJNI.KeyStoreWriter_write(swigCPtr, this, Document.getCPtr(arg0), arg0);
  }

  public boolean del(Slice arg0) {
    return cbforestJNI.KeyStoreWriter_del__SWIG_0(swigCPtr, this, Slice.getCPtr(arg0), arg0);
  }

  public boolean del(java.math.BigInteger arg0) {
    return cbforestJNI.KeyStoreWriter_del__SWIG_1(swigCPtr, this, arg0);
  }

  public boolean del(Document arg0) {
    return cbforestJNI.KeyStoreWriter_del__SWIG_2(swigCPtr, this, Document.getCPtr(arg0), arg0);
  }

  public void rollbackTo(java.math.BigInteger arg0) {
    cbforestJNI.KeyStoreWriter_rollbackTo(swigCPtr, this, arg0);
  }

}
