/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.couchbase.lite.cbforest;

public class SWIGTYPE_p_forestdb__Document {
  private long swigCPtr;

  protected SWIGTYPE_p_forestdb__Document(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_forestdb__Document() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_forestdb__Document obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

